# ONE SIMPLE PIPELINE - Deploy GameStore
name: Deploy GameStore

# Run when you push to main
on:
  push:
    branches: [ main ]

# Deploy job
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get code
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
